--- Generate Locales/Changelog.enUS.lua from CHANGELOG.md, so the window's What's new page and
--- the file people read on GitHub are one text. `make changelog` writes it; the spec in
--- Tests/spec/changelog_spec.lua fails while the generated file is behind.
---
--- Markdown understood: `## ` version headings, `- ` bullets with indented continuation lines,
--- plain paragraphs, and a blank line as a group break. Backticks are dropped. Nothing else is
--- interpreted, so a nested list or a link comes through as written.
local Changelog = {}

local SOURCE, OUTPUT = "CHANGELOG.md", "Locales/Changelog.enUS.lua"
-- Generated string literals wrap at this width so the file stays inside luacheck's 120
-- columns with the indent and the entry's flags on the last line.
local WRAP = 68

local function clean(text)
    text = text:gsub("`", ""):gsub("%s+", " ")
    return text:match("^%s*(.-)%s*$")
end

-- A Lua string literal the client reads back as the markdown said: backslashes and quotes
-- escaped for Lua, pipes doubled because a lone one starts a client escape sequence.
local function quote(text)
    text = text:gsub("\\", "\\\\")
    text = text:gsub('"', '\\"')
    text = text:gsub("|", "||")
    return text
end

function Changelog.parse(markdown)
    local versions, version, entry, gap = {}, nil, nil, false
    local function close()
        if entry then
            entry.text = clean(entry.text)
            entry = nil
        end
    end
    local function open(text, bullet)
        close()
        entry = { text = text, bullet = bullet or nil, gap = (gap and #version.entries > 0) or nil }
        version.entries[#version.entries + 1] = entry
        gap = false
    end
    local number = 0
    for line in (markdown:gsub("\r", "") .. "\n"):gmatch("(.-)\n") do
        number = number + 1
        local heading = line:match("^##%s+(.-)%s*$")
        if heading then
            close()
            version = { title = clean(heading), entries = {} }
            versions[#versions + 1] = version
            gap = false
        elseif line:match("^#%s") then
            close()
        elseif line:match("^%s*$") then
            close()
            gap = true
        elseif not version then
            error(string.format("%s:%d: text before the first version heading", SOURCE, number))
        else
            local bullet = line:match("^%-%s+(.*)$")
            if bullet then
                open(bullet, true)
            elseif entry then
                entry.text = entry.text .. " " .. line
            else
                open(line, false)
            end
        end
    end
    close()
    if #versions == 0 then
        error(SOURCE .. ": no version heading found")
    end
    return versions
end

-- Splits after a space where it can. A run with no space is cut hard, but never right after
-- a backslash: the chunks are concatenated back by Lua, so a split escape is a syntax error.
local function pieces(text)
    local list = {}
    while #text > WRAP do
        local cut = WRAP
        while cut > 1 and text:sub(cut, cut) ~= " " do
            cut = cut - 1
        end
        if cut <= 1 then
            cut = WRAP
            while cut > 1 and text:sub(cut, cut) == "\\" do
                cut = cut - 1
            end
        end
        list[#list + 1] = text:sub(1, cut)
        text = text:sub(cut + 1)
    end
    list[#list + 1] = text
    return list
end

local function flags(entry)
    return (entry.bullet and ", bullet = true" or "") .. (entry.gap and ", gap = true" or "")
end

function Changelog.render(versions)
    local out = {
        "-- Generated by Tools/changelog.lua from CHANGELOG.md. Do not edit by hand: edit CHANGELOG.md, then",
        "-- run make changelog. Tests/spec/changelog_spec.lua fails while this file is behind.",
        "local _, R = ...",
        "R.L = R.L or {}",
        "local L = R.L",
        "L.CHANGELOG = {",
    }
    for _, version in ipairs(versions) do
        out[#out + 1] = "    {"
        out[#out + 1] = string.format('        title = "%s",', quote(version.title))
        out[#out + 1] = "        entries = {"
        for _, entry in ipairs(version.entries) do
            local parts = pieces(quote(entry.text))
            for index, part in ipairs(parts) do
                local head = index == 1 and '            { "' or '                .. "'
                local tail = index == #parts and ('"' .. flags(entry) .. " },") or '"'
                out[#out + 1] = head .. part .. tail
            end
        end
        out[#out + 1] = "        },"
        out[#out + 1] = "    },"
    end
    out[#out + 1] = "}"
    return table.concat(out, "\n") .. "\n"
end

function Changelog.generate(markdown)
    return Changelog.render(Changelog.parse(markdown))
end

local function main()
    local file = assert(io.open(SOURCE, "r"))
    local markdown = file:read("*a")
    file:close()
    local versions = Changelog.parse(markdown)
    local output = assert(io.open(OUTPUT, "w"))
    output:write(Changelog.render(versions))
    output:close()
    local entries = 0
    for _, version in ipairs(versions) do
        entries = entries + #version.entries
    end
    print(string.format("Wrote %s: %d versions, %d entries.", OUTPUT, #versions, entries))
end

-- `lua5.1 Tools/changelog.lua` writes the file. require("Tools.changelog") hands the functions
-- to the spec that checks the written file is current, and writes nothing.
if type((...)) ~= "string" then
    main()
end
return Changelog
